import os


CLIENT_ID = os.getenv('TWITTER_CLIENT_ID')

CLIENT_SECRET = os.getenv("TWITTER_CLIENT_SECRET")

ACCESS_TOKEN = os.getenv("TWITTER_ACCESS_TOKEN")

ACCESS_TOKEN_SECRET = os.getenv("TWITTER_ACCESS_TOKEN_SECRET")

API_KEY = os.getenv("TWITTER_API_KEY")

API_KEY_SECRET = os.getenv("TWITTER_API_KEY_SECRET")

BEARER_TOKEN = os.getenv("TWITTER_BEARER_TOKEN")